---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo index
    package:
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:

  - name: install apache package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba on centos
    dnf:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"
